### ISSUE TITLE
unable to run script

### ISSUE THREAD

**Issue by rami-maalouf** [gahjelle/template-aoc-python#3]
I have downloaded the required softwares but when in trying to copy the template i get this error:
```
rami@Ramis-MacBook-Pro ~ % copier gh:gahjelle/template-aoc-python advent_of_code/
No git tags found in template; using HEAD as ref
🎤 year (int)
   2022
🎤 day (int)
   1
🎤 puzzle_name
 
🎤 puzzle_dir
   01

Copying from template version 0.0.0.post12.dev0+f01620b
    create  .
    create  2022
    create  2022/01
    create  2022/01/example1.txt
    create  2022/01/example2.txt
    create  2022/01/aoc202201.py
    create  2022/01/test_aoc202201.py
    create  download_input.py

 > Running task 1 of 1: python ./download_input.py 2022 1
/bin/sh: python: command not found
Traceback (most recent call last):
  File "/Users/rami/Library/Python/3.9/bin/copier", line 8, in <module>
    sys.exit(CopierApp.run())
  File "/Users/rami/Library/Python/3.9/lib/python/site-packages/plumbum/cli/application.py", line 639, in run
    inst, retcode = subapp.run(argv, exit=False)
  File "/Users/rami/Library/Python/3.9/lib/python/site-packages/plumbum/cli/application.py", line 634, in run
    retcode = inst.main(*tailargs)
  File "/Users/rami/Library/Python/3.9/lib/python/site-packages/copier/cli.py", line 71, in _wrapper
    return method(*args, **kwargs)
  File "/Users/rami/Library/Python/3.9/lib/python/site-packages/copier/cli.py", line 294, in main
    self.parent._worker(
  File "/Users/rami/Library/Python/3.9/lib/python/site-packages/copier/main.py", line 632, in run_copy
    self._execute_tasks(self.template.tasks)
  File "/Users/rami/Library/Python/3.9/lib/python/site-packages/copier/main.py", line 214, in _execute_tasks
    subprocess.run(task_cmd, shell=use_shell, check=True, env=local.env)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command 'python ./download_input.py 2022 1' returned non-zero exit status 127.
```

**Comment by gahjelle** [comment]
Hi @psycho-baller 

This is probably the `download_input.py` script not able to read your personal input data.

Have you stored your personal session token either in a config file or as an environment variable as described here? https://github.com/wimglenn/advent-of-code-wim/issues/1
